"""add price_snapshots table

Revision ID: 33dfb9feb98c
Revises: 88b80a46ba34
Create Date: 2026-05-25 23:28:18.463630

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '33dfb9feb98c'
down_revision: str | Sequence[str] | None = '88b80a46ba34'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'snapshot_at', 'source', name='uq_price_snapshots_dedup')
    )
    op.create_index('ix_price_snapshots_ticker_time', 'price_snapshots', ['ticker', 'snapshot_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_snapshots_ticker_time', table_name='price_snapshots')
    op.drop_table('price_snapshots')
    # ### end Alembic commands ###
