"""initial events table

Revision ID: 88b80a46ba34
Revises:
Create Date: 2026-05-25 20:49:28.995430

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '88b80a46ba34'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('FRED', 'SEC_EDGAR', 'FOMC', 'EARNINGS', name='event_source'), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_tickers', sa.ARRAY(sa.String(length=10)), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('FETCHED', 'ANALYZED', 'FAILED', 'IGNORED', name='event_status'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_events_source_external_id')
    )
    op.create_index('ix_events_status_published', 'events', ['status', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_events_status_published', table_name='events')
    op.drop_table('events')
    # Autogenerate doesn't drop ENUM types — orphans them in pg_type otherwise.
    op.execute('DROP TYPE IF EXISTS event_status')
    op.execute('DROP TYPE IF EXISTS event_source')
